### ISSUE TITLE
A huge comment from in the beginning of generated file

### ISSUE THREAD

**Issue by agigao** [fniessen/org-html-themes#109]
Recently, the comment tag started to appear, any ideas where it comes from?

<img width="961" alt="Screen Shot 2020-06-04 at 18 46 18" src="https://user-images.githubusercontent.com/22436648/83774130-62bbc700-a696-11ea-9507-3f503c2bcefd.png">

Cheers,
Giga

**Comment by agigao** [comment]
Hi, thanks for such prompt response!

Well, this is my header source:

```
#+TITLE: X
#+AUTHOR: Giga Chokheli
#+OPTIONS: ^:nil

#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup
#+HTML_HEAD: <style> #content{max-width:1800px;}</style>
#+HTML_HEAD: <style> p{max-width:800px;}</style>
#+HTML_HEAD: <style> li{max-width:800px;}</style
```

Using the latest commit I guess.

# HTML Source screenshot:
<img width="1072" alt="Screen Shot 2020-06-04 at 19 38 22" src="https://user-images.githubusercontent.com/22436648/83777909-09a26200-a69b-11ea-8120-6e8374b3eab0.png">

**Comment by fniessen** [comment]
Well, here an MWE:

    #+TITLE: X
    #+AUTHOR: Giga Chokheli
    #+OPTIONS: ^:nil

    #+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup
    #+HTML_HEAD: <style> #content{max-width:1800px;}</style>
    #+HTML_HEAD: <style> p{max-width:800px;}</style>
    #+HTML_HEAD: <style> li{max-width:800px;}</style

    * Here

    also

    * There

It just gave:

![image](https://user-images.githubusercontent.com/1748469/83778711-5c741d80-a68b-11ea-82ca-5a61dd28a394.png)

Problem does not seem on this side?  (I'd expect a lot of reactions - and the code has not been updated for a while...)

**Comment by hskalin** [comment]
I am experiencing the same problem

```
#+TITLE: X
#+AUTHOR: Giga Chokheli
#+OPTIONS: ^:nil

#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup
#+HTML_HEAD: <style> #content{max-width:1800px;}</style>
#+HTML_HEAD: <style> p{max-width:800px;}</style>
#+HTML_HEAD: <style> li{max-width:800px;}</style

* Here

also

* There
```

![image](https://user-images.githubusercontent.com/49724493/85196626-25437480-b2f9-11ea-92ba-ade8ac62ffe1.png)

**Comment by SarthakAdhikari** [comment]
I'm facing the same problem.

```
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup
#+HTML_HEAD: <style> #content{max-width:1800px;}</style>
#+HTML_HEAD: <style> p{max-width:800px;}</style>
#+HTML_HEAD: <style> li{max-width:800px;}</style

* Test header
This is a test message.
```

![orgmodeheader](https://user-images.githubusercontent.com/13420710/95161092-c31c5b80-0791-11eb-9d83-23e920de6d5f.png)

As of this comment, the latest commit ID is `7e4e2ec`. 

System details:
Emacs Version: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20) of 2020-08-28
Org Version: Org mode version 9.3 (release_9.3 @ /usr/local/share/emacs/27.1/lisp/org/)
Browser: FireFox 81.0 (64-bit)
OS: Ubuntu 20.04.1 LTS

**Comment by SarthakAdhikari** [comment]
Turns out, I missed the closing ">" in </style>.

**Comment by fniessen** [comment]
Indeed. Thank you for checking this out!
