### ISSUE TITLE
Bigblow: Quitting the review panel.

### ISSUE THREAD

**Issue by AKielhorn** [fniessen/org-html-themes#111]
One of my readers clicked on a TODO item and was in review mode.

And no hint how to quit it.

I have added the following:
`
diff --git a/styles/bigblow/js/hideshow.js b/styles/bigblow/js/hideshow.js
index 72684d8..a640bcc 100644
--- a/styles/bigblow/js/hideshow.js
+++ b/styles/bigblow/js/hideshow.js
@@ -310,7 +310,8 @@ function hsAddReviewingPanels() {
                             + '(out of ' +  nbReviewTotalTasks + ' tasks)<br>'
                             + 'Shortcuts: '
                             + '<span class="hsReviewButton" onclick="hsReviewTaskNext()">r (next)</span> - '
-                            + '<span class="hsReviewButton" onclick="hsReviewTaskPrev()">R (previous)</span>'
+                            + '<span class="hsReviewButton" onclick="hsReviewTaskPrev()">R (previous)</span><br>'
+                            + '<span class="hsReviewButton" onclick="hsReviewTaskPrev()">q (quit)</span>'
                             + '</div>');
         }
         else {
@@ -318,7 +319,8 @@ function hsAddReviewingPanels() {
                             + '(out of ' +  nbReviewTotalTasks + ' tasks)<br>'
                             + 'Shortcuts: '
                             + '<span class="hsReviewButton" onclick="hsReviewTaskNext()">r (next)</span> - '
-                            + '<span class="hsReviewButton" onclick="hsReviewTaskPrev()">R (previous)</span>'
+                            + '<span class="hsReviewButton" onclick="hsReviewTaskPrev()">R (previous)</span><br>'
+                            + '<span class="hsReviewButton" onclick="hsReviewTaskPrev()">q (quit)</span>'
                             + '</div>');
         }
     });
`

**Comment by fniessen** [comment]
Dear @AKielhorn , Thanks for this!  (and sorry for the big jetlag.)
However, the patch is not correctly displayed here, and I'm wondering why you do have twice info about "R (previous)". Is it intended?

**Comment by AKielhorn** [comment]
Even after adding the code tags it did not improve, here it is attached:

[html-themes.txt](https://github.com/fniessen/org-html-themes/files/5521981/html-themes.txt)

The first line has a "-" that is not shown, in fact I just added a `<br>` to that line.

**Comment by fniessen** [comment]
Merged.  Thanks a lot for the improvement!

**Comment by olberger** [comment]
I guess this lacked #159 for a little fix.
