### ISSUE TITLE
Warning - image broken? 

### ISSUE THREAD

**Issue by samspo** [fniessen/org-html-themes#115]
Hello,

When I export a "warning block" in readtheorg, it seems that there is a broken link to the image that illustrates the warming (see image below, same with firefox and chrome).
Am I doing something wrong ?

<img width="144" alt="Capture d’écran, le 2020-09-22 à 16 47 19" src="https://user-images.githubusercontent.com/1280210/93935878-4d28e680-fcf3-11ea-98d0-8988f2c43617.png">

**Comment by fniessen** [comment]
Dear @samspo , no, you're not doing anything wrong.  Something I need to fix...

**Comment by samspo** [comment]
Thanks for your answer ! (any idea of what I can do directly in the html file to correct that by hand? I'm sorry for this stupid question)

**Comment by leodumont** [comment]
Same issue here. I guess something is wrong with awesome font dependency? But I did not really take the time to debug it

**Comment by fniessen** [comment]
Dear @samspo and @leodumont , I've reverted a bad commit, with commit 39a8ce2.
This should be solved as soon as the github.io "site" will get the fresh copy of the CSS.
Closing the ticket now, but reopen it if needed.
