### ISSUE TITLE
Githubg web site (SETUP distribution) broken

### ISSUE THREAD

**Issue by gmounie** [fniessen/org-html-themes#116]
Githubg web site (SETUP distribution) seems broken to me. May be it's related to directory name change ?

**Comment by fniessen** [comment]
It's working for me, at the moment.

Check out the source of your HTML page, and see whether you have this:


    <link rel="stylesheet" type="text/css" href="https://fniessen.github.io/org-html-themes/src/readtheorg_theme/css/htmlize.css"/>
    <link rel="stylesheet" type="text/css" href="https://fniessen.github.io/org-html-themes/src/readtheorg_theme/css/readtheorg.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://fniessen.github.io/org-html-themes/src/lib/js/jquery.stickytableheaders.min.js"></script>
    <script type="text/javascript" src="https://fniessen.github.io/org-html-themes/src/readtheorg_theme/js/readtheorg.js"></script>

**Comment by brettviren** [comment]
The GH pages for this repo appear to be down in their entirety.

https://fniessen.github.io/org-html-themes/
https://fniessen.github.io/

Both return 404.  Was there maybe a change in the GH Pages settings for this repo?

I also check with some random "up" checker and it confirms

https://isitup.org/fniessen.github.io

(thanks for these great themes!)

**Comment by fniessen** [comment]
@brettviren, thanks for letting me know.

However, I've just tested the export, and it does work, right?  The HTML file contains the following directives:


    link rel="stylesheet" type="text/css" href="https://fniessen.github.io/org-html-themes/src/readtheorg_theme/css/htmlize.css"/>
    link rel="stylesheet" type="text/css" href="https://fniessen.github.io/org-html-themes/src/readtheorg_theme/css/readtheorg.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://fniessen.github.io/org-html-themes/src/lib/js/jquery.stickytableheaders.min.js"></script>
    <script type="text/javascript" src="https://fniessen.github.io/org-html-themes/src/readtheorg_theme/js/readtheorg.js"></script>

Do you confirm that?

So, the only problem is that the "web site" is not visible as it should... Nope, no change...

Just checked the settings; they look normal to me:

![image](https://user-images.githubusercontent.com/1748469/100238847-f62cd100-2f30-11eb-891e-fdbcab6a484e.png)

Any idea?

Thanks for your comment. BTW, I really would like to add a couple of other themes I've made over time, for Org. And a ReadTheProject one, where one big Org file would be presented as a web site, with previous/next buttons between H1 or something along those lines...

Would you have some knowledge about how to improve the TOC on the left side (of RTO), it'd be appreciated... (not showing a vertical slider when the TOC is short).

**Comment by brettviren** [comment]
So far, I see no problems with the actual theme mechanics, just the GitHub serving.  The GH Pages settings you show look all good to me.  So, GH must be having some internal problems.  FWIW, I can access other github.io GH Pages sites.  

Your new ReadTheProject theme sounds fantastic!  I use both RTO and BB for various software manuals and like them both.  The prev/next pattern could be useful for more linear tutorial type documents.  In general, more themes the better.  Your work is filling an important niche in the org landscape!

My JS/CSS skills are rather poor.  I've played with a fixed TOC but have yet to make anything come out even close to how your have things.  Here's an example of my poor attempt at DIY, https://brettviren.github.io/zio/messages.html

**Comment by fniessen** [comment]
Thanks for your comments. The RTP theme is still in the PLAN mode... though, it will come...

For the GitHub serving, I'll let you close this as soon as this seems resolved?  If no improvement in the coming days, we can query the GH team...

**Comment by vikasrawal** [comment]
Did anyone manage to figure out what is wrong? It does not look like github pages is serving this?

**Comment by brettviren** [comment]
I fear my original 404 reports were red herrings as the URLs were for directories and not files.  I think it is GitHub Pages SOP to not provide a default "index.html" for a directory.  Sorry for adding that confusion.

In any case, today, here is a 404 on a directory and followed by a success on a specific file:

```
❯ wget  https://fniessen.github.io/org-html-themes/
--2021-05-27 15:05:05--  https://fniessen.github.io/org-html-themes/
Resolving fniessen.github.io (fniessen.github.io)... 185.199.109.153, 185.199.108.153, 185.199.111.153, ...
Connecting to fniessen.github.io (fniessen.github.io)|185.199.109.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-05-27 15:05:06 ERROR 404: Not Found.

❯ wget https://fniessen.github.io/org-html-themes/src/readtheorg_theme/css/htmlize.css
--2021-05-27 15:05:52--  https://fniessen.github.io/org-html-themes/src/readtheorg_theme/css/htmlize.css
Resolving fniessen.github.io (fniessen.github.io)... 185.199.109.153, 185.199.108.153, 185.199.111.153, ...
Connecting to fniessen.github.io (fniessen.github.io)|185.199.109.153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10146 (9.9K) [text/css]
Saving to: ‘htmlize.css’

htmlize.css                   100%[==============================================>]   9.91K  --.-KB/s    in 0.001s  

2021-05-27 15:05:52 (11.8 MB/s) - ‘htmlize.css’ saved [10146/10146]
```
