### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by jon-mqn** [fniessen/org-html-themes#117]
404 Page not found error for https://fniessen.github.io/ and the one liners like https://fniessen.github.io/org-html-themes/org/theme-readthedocs.setup

Must be fairly recent (past couple days)

**Comment by fniessen** [comment]
Just opened ticket "404 on GitHub Pages" (#920730).

Though, the SETUPFILE directive:

    #+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup

still does work for me!?

**Comment by jon-mqn** [comment]
Wow, that actually does work for me too .. which is what I thought I had before. I guess I thought I switched to the new one-liner for this document but still hadn't? And then I just got distracted by the 404. 

But all is well. Thanks!

**Comment by fniessen** [comment]
Well, not everything is OK still: http://org-html-themes.github.io/ should work (as I had enabled GitHub Pages) but does not.

Indeed, your problem is solved.

**Comment by kidd** [comment]
I'm not sure when I copied the url, but what I had in my org files is:
`https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup`, and this doesn't work :/.
