### ISSUE TITLE
Support source code highlighting

### ISSUE THREAD

**Issue by dareenzo** [fniessen/org-html-themes#118]
First of, @fniessen this is a great project, thanks!

Could you add support for source code highlighting?

**Comment by fniessen** [comment]
Dear @dareenzo , could you be more explicit?
Currently, code blocks have a background color, and the tokens are highlighted correctly, depending on the language.
What else are you talking of?  Could you give examples?

**Comment by dareenzo** [comment]
Hi,

I'm talking of having the tokens highlighted. Here is an example of an export using the readtheorg theme
the code block has white background and tokens are not highlighted.

I also checked the browser's console and no errors were logged.

![Screenshot from 2020-12-02 18-13-17](https://user-images.githubusercontent.com/6130991/100899045-1547d780-34ca-11eb-8eee-40bd75e21a4e.png)

**Comment by fniessen** [comment]
The code block background is white, different from the normal background -- I clone ReadTheDocs' Sphinx theme, and so is it there... so, I'm respecting that too. Try BigBlow for another presentation.

For the tokens highlighting, it does work:

![image](https://user-images.githubusercontent.com/1748469/100903211-eaf41b00-34c5-11eb-9cf0-21421dc9c22f.png)

I guess your Emacs settings aren't correct. You must declare the languages you'll support. See my Emacs config for more information (emacs-leuven repository).

**Comment by ChanderG** [comment]
In case someone else comes here with the same issue, this is what solved it for me: https://stackoverflow.com/a/24087061
