### ISSUE TITLE
https://fniessen.github.io is down, so themes are not loaded

### ISSUE THREAD

**Issue by GregorySchwartz** [fniessen/org-html-themes#119]
https://fniessen.github.io is not found, so the themes are not being loaded.

**Comment by GregorySchwartz** [comment]
Looks like it may just be a change to links.

**Comment by fniessen** [comment]
Dear @GregorySchwartz , Not sure to understand everything yet.
But do you confirm that the URL https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup does return something for you as well?

**Comment by fniessen** [comment]
PS - Why did you close the ticket?

**Comment by GregorySchwartz** [comment]
It must have been down when I was checking out one of my code websites as it was not responding for me. I switched to the new version (which changed the link to the setup file) and it worked, so I closed this issue assuming it was just an outdated link.
