### ISSUE TITLE
Q: Has "footref" font-size 170% intentionally?

### ISSUE THREAD

**Issue by fpatz** [fniessen/org-html-themes#123]
I would have expected a footnote reference to be a smaller-than-body superscript. OTOH, it becomes very prominent this way and easily clickable. I'd assume that was your intention?

https://github.com/fniessen/org-html-themes/blob/fbad4f0fbbd539d59e4bd77453164bd2dabd0a9d/src/readtheorg_theme/css/readtheorg.css#L1043

**Comment by fniessen** [comment]
Hello @fpatz. My intention always has been to "clone" - as closely as possible - the "Read the Docs" Sphinx theme. I don't know anymore whether the footnote is like that in that theme. If you can find out, I'll be pleased to make a change, if needed.

**Comment by fpatz** [comment]
It looks like "Read the Docs" has font-size: 90% for footnote-reference: https://github.com/readthedocs/sphinx_rtd_theme/blob/1f7bdc1c36438b3900a434b69636c9b0325d0888/src/sass/_theme_rst.sass#L249
