### ISSUE TITLE
anyway to change the heading for the laert, tip box?

### ISSUE THREAD

**Issue by cryoguy** [fniessen/org-html-themes#124]
I am using the readtheorg theme. Is there a way to name the heading instead of the generic `tip`, `alert` etc?
 
```
#+begin_tip
This is extra info
#+end_tip
```

**Comment by fniessen** [comment]
Dear @cryoguy , that'd be a question for the Org mode list, not for me ;-)

Note that I definitely would support:
- The addition of "note", "tip" and "warning" admonitions, at the very least, in the standard -- by that, I mean, they would become first-class citizens, and they could be highlighted with a different background colour in the Org buffer (waouwh!)
- The addition of a title, what you're asking for.

As a work-around, in the meanwhile, you could have a look at the insertion of org-todo inline tasks (C-c C-t). Not a real solution, but, there, you do have titles for the blocks. See my other Org repos (ref card) for typical usage of that "environment".

**Comment by fniessen** [comment]
Please come back here, inserting any answer you'd receive from the mailing list, in this "issue".

**Comment by cryoguy** [comment]
What I mean is the `tip` (or whatever the admonitions used) on top of the tip box, which is defined in CSS with `::before`.

**Comment by fniessen** [comment]
Not sure to follow everything... Could you submit a change in the CSS, showing that we still get the same look and feel for standard admonitions, and potentially something more (when you want to change the title of the admonition)?

If possible, the idea would be to have the default heading if none is given -- like in the ReadTheDocs --, but to be able to change that.
