### ISSUE TITLE
Custom user themes repository?

### ISSUE THREAD

**Issue by AtomicNess123** [fniessen/org-html-themes#125]
Have other users shared their customized themes in some repository? This would be great. Thanks!

**Comment by fniessen** [comment]
Dear @AtomicNess123. Currently, not yet. But that could be done, and would be a good place for that.
I'm intending to add 1 or 2 other themes in the medium term - once I'll have time, so this is clearly some library of themes that could/will grow.
If you're interested, you can drop me a PR.
