### ISSUE TITLE
[feature request] split theme files into 2 parts, code and prose

### ISSUE THREAD

**Issue by ukaszg** [fniessen/org-html-themes#126]
Could the "*.setup" files be split? one part containing only styles for source code blocks, 2nd part - the rest.

This way you could pick colors for code and other things separately (ie. white bacground for the document, solarized dark for source code quotes).

**Comment by fniessen** [comment]
Dear @ukaszg , I'm not sure about this.  That would make it more complex, having to load 2 SETUPFILES.  (And, for me, the code block styling is part of the overall styling of the page, BTW.)

Don't forget you can do it on your own: you can always have a private SETUPFILE that you load after loading the theme, nope?
