### ISSUE TITLE
Foldable text in html 

### ISSUE THREAD

**Issue by sbilmis** [fniessen/org-html-themes#127]
Hi, 
I would like to see a feature of foldable text in the HTML exported document. For instance, the question will be shown but for the solution, one needs to click the show answer button. 
You can see an example [in this web-page ](https://aaltoscicomp.github.io/python-for-scicomp/parallel/) which is created by sphinx using a theme by ReadTheDocs. 

<img width="729" alt="image" src="https://user-images.githubusercontent.com/6851144/109056672-c76df480-76f1-11eb-95b0-f3f139e477f2.png">

Can this be done with org-export?

Thanks for creating such a great theme btw.

Best,
Selcuk

**Comment by nico202** [comment]
What about html details tag? Example:
```
#+title: Details html tag

* Example

  You can find more info

  #+begin_export html
  <details>
  #+end_export
[[https://www.w3schools.com/TAGS/tag_details.asp][here]]
  #+begin_export html
  </details>
  #+end_export
```

**Comment by sbilmis** [comment]
Thanks for the answer.  That solves my problem.
