### ISSUE TITLE
Youtube in readtheorg?

### ISSUE THREAD

**Issue by Ypot** [fniessen/org-html-themes#128]
Is it possible to embed youtube or other videos in the exported HTML?
Gifs work great though ^^

**Comment by fniessen** [comment]
Dear @Ypot , you embed images in the HTML?  Wasn't yet aware of that. How do you do?
PS - That's more an HTML question...

**Comment by Ypot** [comment]
> Dear @Ypot , you embed images in the HTML? Wasn't yet aware of that. How do you do?
> PS - That's more an HTML question...

I embed images just attaching them. Readtheorg makes the work:
https://we.tl/t-BaraUS23M9

**Comment by fniessen** [comment]
Please have a look at how I did for my home page.  The source code is in Git...

**Comment by matiya** [comment]
I use the following to embed videos:

`#+begin_export html
<video controls="controls" src="../assets/vid.mp4" width="100%">
This browser can't display the video
</video>
#+end_export
`
