### ISSUE TITLE
Hosted css is 404-ing

### ISSUE THREAD

**Issue by shlomiv** [fniessen/org-html-themes#129]
Hi, for some reason I am getting 404 on all the css's (such as https://fniessen.github.io/org-html-themes/styles/readtheorg/css/readtheorg.css) 

Is there a different URL to use?

**Comment by fniessen** [comment]
Please check out the URL in the theme-readtheorg.setup file.

Correct URL:
https://fniessen.github.io/org-html-themes/src/readtheorg_theme/css/readtheorg.css

**Comment by shlomiv** [comment]
Oh! Thanks, will update.
