### ISSUE TITLE
Table of contents in ReadTheOrg doesn't scroll *

### ISSUE THREAD

**Issue by dctoedt** [fniessen/org-html-themes#13]
Apologies if this is double-posted; I tried a few days ago but don't see it.

I've tried doing a couple of documents with ReadTheOrg.  It's an *awesome* theme; I'd like to use it for a number of documents.

One of my documents is really long.  I've noticed some issues with the left-sidebar table of contents:

1. The left sidebar table of contents doesn't scroll.  

2.  When I expand a section by clicking on its heading in the left sidebar TOC (thus exposing the "sub-TOC" for that section):

2.1  the expanded sub-TOC doesn't scroll either; and

2.2 there doesn't seem to be a way to re-collapse the expanded TOC.

**Comment by fniessen** [comment]
I've added a scrollbar in the TOC. Please let me know what you think of it.

**Comment by dctoedt** [comment]
The scrolling looks nice.  I see the left-sidebar TOC doesn't collapse anymore?

**Comment by fniessen** [comment]
Could you be more specific?  I'm not aware having changed anything regarding collapsing...

In my opinion, the TOC never collapsed, but I may miss your point...

**Comment by fniessen** [comment]
Closing this in the absence of further news.
