### ISSUE TITLE
Question: Readtheorg theme - changing location of exported html with local setup loses style and formatting

### ISSUE THREAD

**Issue by Delanii** [fniessen/org-html-themes#130]
This is maybe a basic question from a beginner, but I have noticed that after using `readtheorg` theme for exporting html, when I move the resulting file to different folder tree I lose all the styling and formatting.

I guess that is because the style files (maybe also script files?) are hyperlinked to exported document as references and are not actually contained in the exported file. Is that correct? How can that be changed to get "standalone" HTML file?

I have tryed to modify the setupfile to use `#+INCLUDE` directives but it did not work ...

I would like to thank you for an amazing theme files, that allow beginner like me to kinda "jump right in" and hopefully also for patience while helping me with this.

**Comment by fniessen** [comment]
@Delanii Thanks for the comments.

Indeed, if you change the folder structure, you need to update paths in the SETUPFILE.

Note that the easiest is to have no local SETUPFILE at all!  Simply use #+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup in any Org file, no more needed!
