### ISSUE TITLE
No Demo page found for ReadTheOrg theme

### ISSUE THREAD

**Issue by 0xShree** [fniessen/org-html-themes#131]
404 error for [demo page](https://github.com/fniessen/org-html-themes/blob/master/org/org-mode-syntax-example.txt) on ReadTheOrg theme

**Comment by fniessen** [comment]
https://github.com/fniessen/org-html-themes/blob/master/tests/org-mode-syntax-example.org

**Comment by 0xShree** [comment]
Can you update the link of demo page for ReadTheOrg?

**Comment by fniessen** [comment]
Done. Thx.
