### ISSUE TITLE
Setup file link is down

### ISSUE THREAD

**Issue by TommyX12** [fniessen/org-html-themes#134]
I use the following as my setup file:
```
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup
```

However, since a few month (or longer) ago, this link is no longer accessible. My org files would freeze when opened, and if I try to go to https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup in a browser, I get a 404.

**Comment by fniessen** [comment]
@TommyX12 ,

    #+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-NAME.setup

is the correct path to use -- yes, it has been changed some time ago.
See the README for the up-to-date info.

**Comment by TommyX12** [comment]
Ah, the change was subtle and I didn't notice there was a change. Thank you.

**Comment by TommyX12** [comment]
Seems like the issue still persist; somehow I am able to download the file by going to https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup in a browser, but when I use it as a setupfile in org, emacs shows `Contacting host: fniessen.github.io:443` indefinitely.

**Comment by fniessen** [comment]
Dear @TommyX12 , just tested in the file README.org found in my gutenberg repository, with the following line in preamble:

    #+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup

and I did not get the problem you describe.

I changed it also to bigblow, and it also went fine!?
