### ISSUE TITLE
A dark theme is useful

### ISSUE THREAD

**Issue by ashincoder** [fniessen/org-html-themes#136]
# Hello 

Would love to have a dark theme fro readtheorg.

**Comment by fniessen** [comment]
Dear @ashincoder, thanks for the comment, showing how useful the light theme is.

However, because of lack of time, I won't be able to work on that.  But, would you, or somebody else, I'll accept any PR with pleasure!

**Comment by ashincoder** [comment]
I mean I would love. But I do not have the brain to do such thing. I am amateur who just takes stuff and edits it.
