### ISSUE TITLE
Code labels no longer highlighted on mouseover (i.e., "(ref:sc)" links)

### ISSUE THREAD

**Issue by Stwerp** [fniessen/org-html-themes#144]
I'm using ReadTheOrg theme via the SETUPFILE recommendation.

Filed generated in the November of 2021 include highlighting for mouse over of code links. Example of the org code for this:

```
You can also add a -r switch which removes the labels from the source code. With the -n switch, links to these references will be labeled by the line numbers from the code listing, otherwise links will use the labels with no parentheses. Here is an example:

(save-excursion                  ; (ref:sc)
  (goto-char (point-min)))       ; (ref:jump)

In line [(sc)](https://github.com/fniessen/org-html-themes/blob/master/tests/(sc)), we remember the current position. [Line (jump)](https://github.com/fniessen/org-html-themes/blob/master/tests/(jump)) jumps to point-min.

```

When this is exported to HTML, hovering on the "(sc)" links in the last paragraph should highlight the line in the code block. Files were doing this, but something has changed since the fall.

I'm not entirely sure where this comes from, but the exported HTML that /does not/ highlight code lines is missing a block of javascript. The missing code seems to be:

```
<script type="text/javascript">
// @license magnet:?xt=urn:btih:1f739d935676111cfff4b4693e3816e664797050&amp;dn=gpl-3.0.txt GPL-v3-or-Later
<!--/*--><![CDATA[/*><!--*/
     function CodeHighlightOn(elem, id)
     {
       var target = document.getElementById(id);
       if(null != target) {
         elem.classList.add("code-highlighted");
         target.classList.add("code-highlighted");
       }
     }
     function CodeHighlightOff(elem, id)
     {
       var target = document.getElementById(id);
       if(null != target) {
         elem.classList.remove("code-highlighted");
         target.classList.remove("code-highlighted");
       }
     }
    /*]]>*///-->
// @license-end
</script>
```

I've seen some other issues here that mention the "magnet" code. Is this section of code generated by an `org`/`ox-export` engine, or was it part of the `ReadTheOrg` theme that was removed? I can't quite figure out where it came from, or what I've done to remove it.

This happens when using `emacs -Q` and exporting from org. The top of my org file has:
```
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
# Change the background of source block.
#+HTML_HEAD: <style>pre.src{background:#343131;color:white;} </style>
```
My fully-working export was from Nov 5. (But on my end, I've changed computers and had an org/emacs/package updates since then, which may be the culprit.)

Thanks for your work on this, and apologies if this is not a problem on your end.

**Comment by Stwerp** [comment]
... Aaaaand I spoke too soon! Looks like a variable was changed, and this is coming form org-export.

A bit more googling after I posted brought me to [this reddit thread]( https://www.reddit.com/r/emacs/comments/humgny/getting_rid_of_excess_header_in_org_html_export/ ) where it mentioned a variable.

Executing
```
(setq  org-html-head-include-scripts t)
```
will include the necessary script and get highlighting working again. Looks like it was an org change, and nothing on your end!

**Comment by fniessen** [comment]
DEar @Stwerp. Thanks for adding information...
