### ISSUE TITLE
The display of admonition is strange

### ISSUE THREAD

**Issue by tanioka256** [fniessen/org-html-themes#149]
The contents of `test.org` are as follows:

```
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup

* Head A

#+begin_note
Note A
#+end_note

* Head B

BBBBB
```

I exported it to html as follows.

    $ LANG=C emacs --batch -Q --visit test.org --eval "(org-html-export-to-html)"

The display of `test.html` in Firefox looks like this:

![image](https://user-images.githubusercontent.com/18693480/173601118-3e0d0c7a-e20c-4d89-b15d-1de4b519ae24.png)

A section following a note appears in that note!

Environment:
* Ubuntu 18.04
* emacs-version 27.1
* org-version 9.3 (built-in)

**Comment by tanioka256** [comment]
When using revisions prior to 5f74b76 with local clones, the display was as expected.

    $ git clone https://github.com/fniessen/org-html-themes.git
    $ cd org-html-themes
    $ git checkout -b test2 5f74b76^

The contents of `test2.org` are as follows. This differs from the [above](https://github.com/fniessen/org-html-themes/issues/149#issue-1270943401) only in the reference to `SETUPFILE`.

```org
#+SETUPFILE: org/theme-readtheorg-local.setup

* Head A

#+begin_note
Note A
#+end_note

* Head B

BBBBB
```

Convert this to an HTML file as follows:

    $ LANG=C emacs --batch -Q --visit test2.org --eval "(org-html-export-to-html)"

The display of `test2.html` is as follows.

![img](https://user-images.githubusercontent.com/18693480/178090342-81d0939c-6fbe-47d9-991d-eb061da4e10b.png)

This is the expected display result.

**Comment by olberger** [comment]
This is also reproducible on the README.org file, provided one compiles it with 
```
#+SETUPFILE: org/theme-readtheorg-local.setup
```
Hope this helps,

**Comment by tanioka256** [comment]
The problem no longer occurs with revision d8cf56bb1fa0280fe5b1a2b335dd6637f1964851.
