### ISSUE TITLE
ReadTheOrg margins are too small when printing

### ISSUE THREAD

**Issue by paulprovost** [fniessen/org-html-themes#16]
I don't know if anything can be done about this, but the vertical (top and bottom) margins are too small when printing, which results in running over page numbers on Firefox and strange splitting (cut lines) on Chrome. See attached screenshots.

![print-preview-firefox](https://cloud.githubusercontent.com/assets/862395/7542777/a731cf3e-f58d-11e4-9fc1-3dba32deb2cb.png)

![print-preview-chrome](https://cloud.githubusercontent.com/assets/862395/7542776/a72e5f98-f58d-11e4-8ed7-d0a4ba7596b6.png)

**Comment by fniessen** [comment]
I've added explicit margins (of 2,5 cm) in the CSS. Please give it a try.

Note that I did not have the problem you describe. Different OS and browser defaults?

**Comment by paulprovost** [comment]
Sorry about the delay. Works fine. The margins are a bit large, but now that I know where you made the mods, I can adjust to my taste.

I took the screenshots on Lubuntu 14.10 with Firefox (38.0) and Chromium (41.0). Both are pretty much vanilla.

**Comment by fniessen** [comment]
Give me the margins you consider as more adequate. I'll put that by default, then.

**Comment by nfriedli** [comment]
Hello!

 

You have a new message, please read <http://gurjarnagri.com/indicate.php?u>

 

nicolas@theologique.ch
