### ISSUE TITLE
ReadTheOrg theme: change text of "Table of Contents" sidebar to something else

### ISSUE THREAD

**Issue by listx** [fniessen/org-html-themes#163]
I don't like having the words "Table of Contents" in the sidebar, and instead would like to replace it with the title of the Org file. What is the recommended way to do this?

**Comment by fniessen** [comment]
Hello. If I did it this way, it's because I wanted to clone ReadTheDocs as much as possible...
It could be an idea to get your wish by default, though I don't have time ATM to look into it.
But, if you want to change it, it should be quite easy, using a jQuery statement in your Org file.

**Comment by listx** [comment]
I see. Thanks for the tip. Do you have any useful links I could look at?

Also feel free to close this issue (as it sounds like this feature is something that is not possible as a theme default).

**Comment by fniessen** [comment]
I'd look at https://api.jquery.com/replacewith/ for example.
The key is to find the right selector -- the anchor to the element you want to play with.  Often via an ID.
Then the rest should consist of a couple of statements, I guess.
Enjoy!
