### ISSUE TITLE
Table header has white text on white background

### ISSUE THREAD

**Issue by Nobody-86** [fniessen/org-html-themes#164]
In the file [bigblow.css](https://github.com/fniessen/org-html-themes/blob/master/src/bigblow_theme/css/bigblow.css), the color definition of the table header is chosen somewhat unfavorably:
```
th
{
    border-width: 1px 2px;
    border-color: white;
    background-color: #2061A2;
    color: white;
}
```
The following color selection would remedy the situation.
```
th
{
    border-width: 1px 2px;
    border-color: white;
    background-color: #2061A2;
    color: black;
}
```

As a temporary solution the following header definition can be used
`#+HTML_HEAD: <style>th{color: black}</style>`

**Comment by fniessen** [comment]
@Nobody-86 I don't share the same rendering experience as yours.

With your setting:
![image](https://github.com/fniessen/org-html-themes/assets/1748469/48f1e2df-5c1d-46ec-897a-4868a0b3da8b)

With the default one:
![image](https://github.com/fniessen/org-html-themes/assets/1748469/7e33c776-bb65-45a6-9498-2d355365581c)

The contrast is better with white on dark blue, IMHO.
