### ISSUE TITLE
Bigblow theme: Collapsing and expanding sections with the mouse doesn't work (any longer)

### ISSUE THREAD

**Issue by dieter-wilhelm** [fniessen/org-html-themes#167]
Hello,

thank you for the bigblow theme, it's great! I loved especially the folding capability, but, unfortunately, since this week it isn't working any longer.  I can't fold the headlines with the mouse any longer, it's only working with the "collapse all" and "expand all" buttons!

The other problem I got is that the line in "this section" appears now twice! (Please see in the attachment, this didn't occur when I tested bigblow in the beginning).  Could you please tell me what I'm doing wrong?

Thank you for your support

  Dieter

![bigblow_2022-12-13](https://user-images.githubusercontent.com/11454481/207382472-8a2cd10b-9bdb-4b1e-add1-fd71556dae79.png)

**Comment by fniessen** [comment]
Dear @dieter-wilhelm . OK, sure. No problem.

FYI, I do have a repo emacs-leuven, with my Org config (emacs-leuven-org.el).

**Comment by dieter-wilhelm** [comment]
I'm closing this issue, since it was indeed a problem in my org-file and not in the bigblow theme :-).

PS: By the way, is it possible to enlarge the levels at which the headlines are folded (from 3 to 4)?

**Comment by fniessen** [comment]
@dieter-wilhelm Thanks for the update.

Could you share what your finding was, regarding the issue at hand?  Maybe that would ring a bell for someone else, in the future?

PS - Wanna try a PR for the max folding level?

**Comment by dieter-wilhelm** [comment]
> Could you share what your finding was, regarding the issue at hand? Maybe that would ring a bell for someone else, in the future?
> 
If I remember correctly it came as a side-effect from a typo in one of my countless blocks like the following

`#+begin_src R`
`..`
`b#+end_src`  <- note the **b**

it botched my org file in various respects (e.g. backups, etc..)

> PS - Wanna try a PR for the max folding level?

I've got only very basic html knowhow and feel not capable to achive this on my own.  Could you maybe outline what would be necessary to enhance the folding?

Thank you
