### ISSUE TITLE
Read The Org does not export border attribute 

### ISSUE THREAD

**Issue by Enrico68** [fniessen/org-html-themes#17]
First of all thanks again for your nice themes! 

I noticed that there is a problem exporting picture with border attribute with this theme (Bigblow is working correctly).
````
#+CAPTION: Frattura provocata da una impropria sezione dello sterno
#+attr_html: :width 300px :border 3px black
#+ATTR_LaTeX: swidth=5cm,angle=90
#+name: Fig.1-1
`````

The picture exported is correctly display with appropriate width but without border.

**Comment by fniessen** [comment]
I'll have a look soon.

Did you look for the source of the problem already, maybe, in the CSS?

**Comment by fniessen** [comment]
Fixed in Git. Will push it to Pirilampo.org this evening.
