### ISSUE TITLE
Default Collapse Behavior on Bigblow

### ISSUE THREAD

**Issue by Nidish96** [fniessen/org-html-themes#171]
Thanks for a great repository!

I was wondering if it is possible to have bigblow launch with all the subsections collapsed by default (collapse all functionality).

Thanks!

**Comment by fniessen** [comment]
Thanks @Nidish96 .

Yes, that could be possible. Though, this is not the foreseen behavior by default. Hence, you should slightly adapt the JS code on your side.

**Comment by Nidish96** [comment]
Thanks for the quick response - is it possible to do this by including a ```#+INFOJS_OPT: ``` in the org file without having to modify the JS code?

**Comment by fniessen** [comment]
I don't know (yet) that option... Give it a try, indeed.
And come back with your results. An example could be welcomed in the README.org file...

**Comment by Nidish96** [comment]
Okay, the closest I could come is by using the export blocks in org. Here's what I did to get this to work (after looking at the relevant variable in https://github.com/fniessen/org-html-themes/blob/master/src/bigblow_theme/js/hideshow.js ):

```
#+BEGIN_EXPORT html
<script>var HS_STARTUP_FOLDED = true;</script>
#+END_EXPORT
```
