### ISSUE TITLE
Inclusion of JavaScript License Info in HTML Output

### ISSUE THREAD

**Issue by koichihanda** [fniessen/org-html-themes#174]
Hello,

Thank you for providing such a wonderful tool.

Recently, I noticed that the JavaScript code and license information are being included in the HTML output. Specifically, the following section appears in the generated HTML:

```
// @license magnet:?xt=urn:btih:e95b018ef3580986a04669f1b5879592219e2a7a&dn=public-domain.txt Public Domain
<!--/*--><!CDATA[/*><!--*/
function CodeHighlightOn(elem, id)
{
   var target = document.getElementById(id);
   if(null != target) {
     elem.classList.add("code-highlighted");
     target.classList.add("code-highlighted");
   }
}

function CodeHighlightOff(elem, id)
{
   var target = document.getElementById(id);
   if(null != target) {
     elem.classList.remove("code-highlighted");
     target.classList.remove("code-highlighted");
   }
}
/*]]>*/-->
// @license-end
```

While I understand that this format might be intended for recognition by certain tools like LibreJS, my project does not utilize these tools. As a result, this code inclusion in the HTML output may cause unintended display issues.

I would kindly request you to consider using standard HTML comment format `<!--` and `-->` to hide the JavaScript code and license information from being displayed in the HTML output. Specifically, please comment out the following section:

```
<!--// @license magnet:?xt=urn:btih:e95b018ef3580986a04669f1b5879592219e2a7a&dn=public-domain.txt Public Domain -->
<!--/*--><!CDATA[/*><!--*/
   [JavaScript code]
/*]]>*/-->
<!--// @license-end -->
```

I believe this modification will result in a cleaner HTML output and align with the requirements of my project.

Thank you for your consideration and prompt action on this matter.

Best regards,

**Comment by fniessen** [comment]
Dear @koichihanda , thanks for your comments!

Would you wanna try to make a PR?  I'd be happy to apply it.

**Comment by koichihanda** [comment]
hello,

thank you for your reply.
I don't know how to fix the issue.
Please forgive me if my remarks are based on misunderstandings.
I would appreciate it if you could suggest a workaround for this issue.

Best regards,

**Comment by koichihanda** [comment]
I found out that the problem was caused by an error in my manuscript.
Same reason as the article below.
https://github.com/fniessen/org-html-subject/issues/109
I am very sorry. m(_ _)m

**Comment by fniessen** [comment]
Glad to see it's solved!
