### ISSUE TITLE
org-publishing not happening

### ISSUE THREAD

**Issue by vkjain** [fniessen/org-html-themes#21]
I had everything working using your org-html-themes. But now the following error comes in the minibuffer while trying to do a org-publish-project

apply: Wrong type argument: listp, #("Fabrice Niessen" 0 15 (:parent (#0)))

Any reason what could have been messed up at my end. 
Thanks
VKJ

**Comment by vkjain** [comment]
If I provide a title to the document like "WLAN CONFIG for the RASPBERRY PI",  then the org-publish-project  throws the error
apply: Wrong type argument: listp, #("WLAN CONFIG for the RASPBERRY PI" 0 32 (:parent (#0)))

This is my header for the org file 
#+STARTUP: indent
#+OPTIONS: toc:nil, author:nil, H:2, f:nil, timestamp:nil, num:0, creator:nil, e:nil
#+OPTIONS: tags:nil
#+INFOJS_OPT: view:info  toc:2

#+SETUPFILE: org-html-themes/setup/theme-bigblow.setup
#+HTML: <script src="js/bootstrap.min.js"></script>

#+title: WLAN CONFIG for the RASPBERRY PI

**Comment by fniessen** [comment]
This does not seem like an Org-HTML-theme problem. Please report on the Org mode ML -- unless it does not make sense there.

**Comment by adbharadwaj** [comment]
This problem can be resolved by reinstalling org package.

**Comment by fniessen** [comment]
@adbharadwaj, Thanks for your comment!
