### ISSUE TITLE
Firefox and Chrome print "Press r or click ..."

### ISSUE THREAD

**Issue by AKielhorn** [fniessen/org-html-themes#22]
When I have a web page with a TODO item, I get the "Press r or click here" box at the bottom when using the Bigblow theme.

When I print the page, both Firefox 38.2.1 and Chrome print this box on every page.

Safari 8.0.8 does not.

Is this a bug in these browsers or do they need some special treatment?

I'm using org 8.2.10, but that shouldn't matter.

Axel

**Comment by fniessen** [comment]
Without having looked at it, I would think this is a missing media query (for printing) in my CSS. Weird, though, that it wouldn't be printed by Safari!?

Org should not matter, no.

Will look into it when I'll have some time.

**Comment by fniessen** [comment]
Is this still a problem?  Any idea on what to change/ how to solve it?

**Comment by AKielhorn** [comment]
It works with the latest Firefox (72).
But now I have a strange experience in Safari:
When I hit Command-P the "P" is interpreted by the javascript and the previous page is printed.
Everything is fine when I select print from the menu.
