### ISSUE TITLE
Linebreaks are not recognized in the exported html

### ISSUE THREAD

**Issue by LukeSwart** [fniessen/org-html-themes#23]
For example, if I have the following:

```
* header
** sub-header
subject-a is not so interesting
I will not write more on subject-a

subject-b is really interesting
I will write more on subject-b
subject-b notes
more subject-b notes
all of these notes are separated by linebreaks
At least they should be

```

It looks like this in the rendered html:

```
* header
** sub-header
subject-a is not so interestingI will not write more on subject-a

subject-b is really interestingI will write more on subject-bsubject-b notesmore subject-b notesall of these notes are separated by linebreaksAt least they should be
```

Is there a way to add linebreaks in between these notes?

**Comment by fniessen** [comment]
May I assume that this question has nothing to do with my HTML themes?

Normally, to add newlines, the Org syntax is \\ (like in LaTeX, in fact). Does that work?

**Comment by LukeSwart** [comment]
Thanks for the reply. I made a mistake so I am closing this issue. I thought `org-html-export-to-html` was adding line breaks (`<br>`) after a newline in the org-file, and I thought the problem was with the HTML themes were not rendering the line breaks.

Your suggestion is correct, except that the Org syntax is \\, which is added at the end of a line in the org-file to create a line break in the HTML. Thus, two newlines create a new HTML paragraph, and it seems like newlines in the org-file are ignored. 

Here is the documentation that solved my issue: http://orgmode.org/org.html#Paragraphs

**Comment by fniessen** [comment]
Oups. Yes, of course, I meant \\ (two slashes, like in LaTeX, as said).

Glad everything's OK for you.
