### ISSUE TITLE
Your readme.ord does nots render that good  using the biglow theme 

### ISSUE THREAD

**Issue by ddewaleffe** [fniessen/org-html-themes#26]
Hi Fabrice,

Been meaning to try org-mode and your stuff for a long time.
Being lazy, I just tried to switched the theme of your readme.org to bigblow... you shoud have a look for yourself... It does not really render as well as I expected. But of course, I imagine that the start hypothesesfor biglow had changed since you wrote the readme.......

So I confirm that bigblow is really good, excellent, stuff but ain't perfect yet :-)
BTW, math stuff does not seem to render in bigblow... (or I did not find the missing incantation).

Cheers,

D.

**Comment by ddewaleffe** [comment]
Math does render in bigblow :-) I had to update to latest org mode...

**Comment by fniessen** [comment]
Dear Dominic,

It does look the way it should - or do you see something specific that's really not good.

Of course, it's a completely different theme, for potentially a different purpose.

Closing this now - still ready to re-open it.

BTW are you really using it Emacs and Org-mode now?
