### ISSUE TITLE
In Chrome the ReadTheOrg Table of Content has a visible scroll bar (even when not needed)

### ISSUE THREAD

**Issue by mistnim** [fniessen/org-html-themes#28]
Shouldn't it be invisible? Like in Readthedoc?

**Comment by fniessen** [comment]
Yes, it should be better, but I had problems trying to do so.  Help welcome.

**Comment by jschwab** [comment]
Just ran into this also.  Can you describe the problems you had?

For my purposes, setting `overflow-y:hidden;` on the table-of-contents seemed OK (in Chromium 51 and Firefox 47), but I imagine that is too naive a solution.

**Comment by fniessen** [comment]
Can't describe which problems I had: a while ago already, I simply played a lot with all combinations of CSS I could think of (but I'm no CSS expert at all -- let's say it!) and never succeeded.

Does your CSS instruction work in all cases you can think of?  Does not need to be complex; just need to be the right instruction...

**Comment by jschwab** [comment]
Sorry, I don't know enough CSS to be able to reason it out either.  I imagine `overflow-y:hidden;` is bad if the TOC is sufficiently long that you can't display it all at once and thus need to scroll within it.

**Comment by fniessen** [comment]
Would you mind testing it with a longer TOC to see if that's right for you?

**Comment by jschwab** [comment]
This does not work well with the longer ToC.  Here are some examples:

https://jschwab.github.io/org-html-themes-issue-28/

**Comment by fniessen** [comment]
Thanks for your (very) helpful links!

Is the correct statement right?

- For short TOC, `overflow-y:hidden` is better.
- Though, for longer TOC, `overflow-y: scroll` is necessary if we want to be able to scroll inside the TOC, and have a look at the structure (OK, that's not good enough anyway, as scrolling should ideally be automatic).

So, at this stage, `overflow-y: scroll` stays a bit better, allowing one to scroll, if wished.

**Comment by jschwab** [comment]
Yes, I agree with that.

**Comment by fniessen** [comment]
So closing this, then, until someone with more expertise could come up with a code allowing to react properly on the real height of the TOC. OK?

**Comment by jschwab** [comment]
Yep, OK by me.
