### ISSUE TITLE
stickytableheaders.js URL no longer valid in theme-readtheorg.setup

### ISSUE THREAD

**Issue by julienchastang** [fniessen/org-html-themes#31]
This URL from  theme-readtheorg.setup is no longer valid

[http://www.pirilampo.org/styles/lib/js/jquery.stickytableheaders.js](http://www.pirilampo.org/styles/lib/js/jquery.stickytableheaders.js)

```
Not Found

The requested URL /styles/lib/js/jquery.stickytableheaders.js was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.
```

**Comment by fniessen** [comment]
Hello, my ISP just moved my account onto a new server. I guess it's related to that.

I'm closing this. Up  to you to reopen it, if that comes back.

**Comment by julienchastang** [comment]
OK thanks, working again. I am a big fan of readtheorg, BTW. I try to promote this project where I can.

**Comment by fniessen** [comment]
Thanks!

Having some competencies in Web responsive design, btw?  I'd be glad to get some help to make a mobile-friendly version out of it...

**Comment by julienchastang** [comment]
Unfortunately, no. I work in the area of scientific computing. I simply re-use the great ideas of others :-)

**Comment by fniessen** [comment]
Never mind.

So do I ;-)
