### ISSUE TITLE
Setting image size in output

### ISSUE THREAD

**Issue by rsuhada** [fniessen/org-html-themes#33]
When using readtheorg theme I'm trying to make the image smaller, e.g. by:

#+ATTR_HTML: :height 50px

Unfortunately, this doesn't do anything. Is there a way to control the image size in the output?

Thank you very much!

**Comment by bamos** [comment]
A hacky workaround I'm using is setting this at the top of my document:

```
#+HTML_HEAD: <style type="text/css">img{ width: 80% }</style>
```

**Comment by fniessen** [comment]
The height was set to auto in RTO. Now removed.
