### ISSUE TITLE
custom IDs work for ReadTheOrg but not Bigblow

### ISSUE THREAD

**Issue by mankoff** [fniessen/org-html-themes#42]
If I have a section with a custom ID like this:

    * About
    :PROPERTIES:
    :CUSTOM_ID: about
    :END:

When I export with ReadTheOrg the URL is `index.html#about` but if I export with bigblow, the URL is `index.html#outline-container-org3a03cbd`

**Comment by fniessen** [comment]
Can't replicate your problem.

See http://screencast.com/t/VTY79wlcMIOK.

If you still have the problem, please provide me with a minimal working example which shows up the problem at hand.
