### ISSUE TITLE
Read The Org: Resources returning 404.

### ISSUE THREAD

**Issue by brenns10** [fniessen/org-html-themes#44]
Recently MathJax stopped rendering on my org documents rendered with this theme.  The only thing I found in the debugger was that the following URL was 404ing: `http://www.pirilampo.org/styles/lib/js/jquery.stickytableheaders.js`.

It appears that the hosted copies of JS are gone.

**Comment by jrmiller82** [comment]
Yup. Same thing here.

**Comment by jsparedes** [comment]
Exploring the site pirilampo.org, the **jquery.stickytableheaders.js** is not  found but **jquery.stickytableheader.min.js** is available.

A thing to mention is that:
- jquery.stickytableheader.min.js is used in **theme-readtheorg-local.setup**
- jquery.stickytableheader.js is used in **theme-readtheorg.setup** which generates 404.

A solution #57 could be to update the content of  theme-readtheorg.setup with **jquery.stickytableheader.min.js**.

**Comment by fniessen** [comment]
Applied fix of Jorge Paredes. Thanks to him.
