### ISSUE TITLE
In Readtheorg theme, Can I unset body width limit? 

### ISSUE THREAD

**Issue by basheewang** [fniessen/org-html-themes#52]
I have a couple of picture which was reduced to smaller, it's difficult to see them clearly. I also have a long table, I don't like the table outside a limit. Please help on this. Thanks.

**Comment by fniessen** [comment]
Hello. Could you write a MWE (Minimal Working Example) of an Org file (minimal!) that exhibits the above problems?  That way, fixing them could be something not too difficult...

**Comment by jlaw9** [comment]
I'm having a similar problem and made a minimal org file as an example.

``` org
#+SETUPFILE: /home/jeffl/Dropbox/orgs/export/org-html-themes/setup/theme-readtheorg.setup

* Header1
| a | b | c | d | f | g | h | i | j | k | l | m | n | o | p | a | b | c | d | f | g | h | i | j | k | l | m | n | o | p |
|---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---|
| a | b | c | d | f | g | h | i | j | k | l | m | n | o | p | a | b | c | d | f | g | h | i | j | k | l | m | n | o | p |
* Header2

#+BEGIN_html
<div class="figure">
<p><img src="http://sachachua.com/blog/wp-content/uploads/2013/05/How-to-Learn-Emacs-v2-Large.png" alt="How-to-Learn-Emacs-v2-Large.png" />
</p>
</div>
#+END_html
```

Exporting that example to html from org generates an html with a large table and the "How to Learn Emacs" PNG. [The PNG](http://sachachua.com/blog/wp-content/uploads/2013/05/How-to-Learn-Emacs-v2-Large.png) is much larger, but is shrunk to fit inside the body (see screenshot below). This leaves a lot of empty space on the side. Is there a way to increase that body limit? Or allow images to be larger than the body?
![image](https://cloud.githubusercontent.com/assets/7592559/23902406/5e8981cc-0897-11e7-8012-13f81ea1e860.png)

Thanks

**Comment by jlaw9** [comment]
Well, I guess other sites that use readthedocs (like [http://networkx.readthedocs.io/en/networkx-1.11/index.html](networkx) have the same body limit so I guess this may just be something I have to deal with.

**Comment by vermiculus** [comment]
@jlaw9 If you're comfy with tweaking the CSS, the element you're looking for is `readtheorg.css:#content.max-width`.

**Comment by jlaw9** [comment]
oh cool thanks @vermiculus. I think that will work

**Comment by malcook** [comment]
FWIW: I override a few styles in my setupfile.org as follows:
```
#+HTML_HEAD: <style> #content{max-width:1800px;}</style>
#+HTML_HEAD: <style> p{max-width:800px;}</style>
#+HTML_HEAD: <style> li{max-width:800px;}</style>
```
Not perfect -  gets most of the way  - improvements welcome.

**Comment by fniessen** [comment]
Dear Malcom, I've inserted your example in the home page, section "Customizing a theme". Thanks for this!
