### ISSUE TITLE
In ReadTheOrg, display only the 1st level entry selected from the tableofcontents

### ISSUE THREAD

**Issue by dinojr** [fniessen/org-html-themes#53]
Let's say I have an org file like

```
* A
** a
** b
* B
** c
** d
```

I'd like to display only
```
** a
** b
```
when I select `*A` from the table of contents. Is there a configuration option for that ?

**Comment by jsparedes** [comment]
It is not an issue relative to the theme. In your org file you only need to put:
`#+OPTIONS: toc:1 `

**Comment by fniessen** [comment]
Here's Jorge Paredes' answer:

    It is not an issue relative to the theme. In your org file you only need to put:
    `#+OPTIONS: toc:1 `

**Comment by dinojr** [comment]
I don't think the toc options is enough to get the behaviour I'm looking for.

toc:1 will always display only the top-level entries:
*A
*B

Whereas I want to display the 2nd level entries of the currently selected 1st-level entry:

* a
* b
displayed when I select *A
and
* c
* d
when I select *B
