### ISSUE TITLE
Applying a theme to an exported agenda view

### ISSUE THREAD

**Issue by RyM21** [fniessen/org-html-themes#55]
Thanks for this great setup. I use a custom agenda command with org-store-agenda-views to publish the day/week agenda and global to-do list to a private website through Dropbox. Is there any way to apply these themes to exported agenda views? I don't see any way to use the #+SETUPFILE option, for example.

**Comment by fniessen** [comment]
Thanks for your interest.

Though, from what I remember, no -- this is not supported. But this is more a feature request for the Org mode ML. I'm sure it'd interest many people out there. Best regards!
