### ISSUE TITLE
table of contents not appearing

### ISSUE THREAD

**Issue by jaydixit** [fniessen/org-html-themes#56]
When I generate HTML from the provided readtheorg.org, the resulting file doesn't have a table of contents. The left pane is blank.

![](https://i.imgur.com/hPGtz6B.png)

Here's the generated HTML:
https://gist.github.com/9f551d6651c138bd4ea17cbd7c651378

**Comment by fniessen** [comment]
I guess you're missing the `toc:t` option, nope?

**Comment by jaydixit** [comment]
Thanks!

> --
sent telephonically
