### ISSUE TITLE
readtheorg theme on pirilampo isn't up to date

### ISSUE THREAD

**Issue by gmorenz** [fniessen/org-html-themes#58]
I just got bit by [this issue](https://github.com/fniessen/org-html-themes/issues/25) as a result. Easy to fix but some warning would have been nice.

Any chance that the remote files could be updated? Otherwise I think the readme should be updated to prefer the local version.

**Comment by fniessen** [comment]
Sure, I should update the remote version. Should do it this week-end. If not done, you can remind it to me.

**Comment by fniessen** [comment]
Done.
