### ISSUE TITLE
FEATURE REQUEST collapsible checkbox lists 

### ISSUE THREAD

**Issue by jstaursky** [fniessen/org-html-themes#59]
I really enjoy using the big blow theme export but when using check boxes I have to write a lot of custom exported html in order to get them how I like. 

The builtin export of the check-boxes only works for very small lists. To keep large lists manageable I implement a collapsible hyperlink tag `<a href="javascript:void(0);"> expandable/collapsible list item </a>` but this results in me having to write alot of my own html and javascript to get things working.

This is what is looks like after I am done rolling my own html and javascript unordered lists (clicking the hyperlinks causes them to expand or contract) 
![image](https://user-images.githubusercontent.com/25406664/27359054-a008f888-55e7-11e7-84f8-77b8dcdc4c3c.png)
Is this something that could be built into the exporter?

**Comment by fniessen** [comment]
Thanks for using BigBlow. However, for everything that concerns the exporter, I have to direct you to the Org mode mailing list. Try to make an ECM (Minimal Working Example) to convey what's the current results of the exports, and how you would want it to look like.
