### ISSUE TITLE
HMTL export does not export the whole file

### ISSUE THREAD

**Issue by claf** [fniessen/org-html-themes#6]
In a document structured as below :

* First title
** First subtitle
todos and stuff

* Second title
todos and stuff

The exported result contains only everything within "First title" and not "Second title". I checked that classic org-mode doesn't have this limitation.

**Comment by fniessen** [comment]
I don't see what you imply. See demo on http://screencast.com/t/WmmtHxiQ.

PS- Don't you miss the "tabs" feature?

**Comment by claf** [comment]
I'm sorry, I did miss the "tabs" feature. My bad, great theme!

**Comment by fniessen** [comment]
You should have a look at https://www.youtube.com/watch?v=DnSGSiXYuOk
 to discover different tricks you can use with Bigblow.

**Comment by claf** [comment]
I will! At least before opening a new issue next time! ;)
