### ISSUE TITLE
code block export issue

### ISSUE THREAD

**Issue by thomas-villagers** [fniessen/org-html-themes#60]
Hi, 

the export of code blocks stopped working for me with an orgmode update mode  from 8.X to 9.0.9. 
All line breaks are removed from the exported html (this does not happen with the "plain" style)

Minimal example: 

`
#+TITLE: Test
#+SETUPFILE: setup/theme-readtheorg-local.setup

#+BEGIN_SRC C
#include <stdio.h>

int main() {
  printf("Hello World");
  return 0; 
}
#+END_SRC
`

![codeblock](https://user-images.githubusercontent.com/1818737/27652910-b0fd37ec-5c3d-11e7-9799-f7b08c57e2df.png)

thank you!

**Comment by fniessen** [comment]
Dear Thomas. I can't replicate your problem: see https://www.screencast.com/t/a68LoSWPtF.

Try to see whether updating your version does solve the problem?

FYI, in the head of the HTML, I do have:

    <link rel="stylesheet" type="text/css" href="http://www.pirilampo.org/styles/readtheorg/css/htmlize.css"/>
    <link rel="stylesheet" type="text/css" href="http://www.pirilampo.org/styles/readtheorg/css/readtheorg.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="http://www.pirilampo.org/styles/lib/js/jquery.stickytableheaders.js"></script>
    <script type="text/javascript" src="http://www.pirilampo.org/styles/readtheorg/js/readtheorg.js"></script>

**Comment by alexvorobiev** [comment]
Hi, I am also having this exact problem after one of the updates of org mode. One thing I noticed is that the generated html formats source code blocks differently. For instance, older org mode did this:

    <div class="org-src-container">

    <pre class="src src-sh">echo 1
    </pre>
    </div>

The new version does this

    <div class="org-src-container">

    <pre><code class="src src-sh">echo 1
    </code></pre>
    </div>

**Comment by fniessen** [comment]
@alexvorobiev Thanks for the information!
