### ISSUE TITLE
Can't scroll the left table of contents

### ISSUE THREAD

**Issue by leolle** [fniessen/org-html-themes#65]
Hi, I am using the styles like this demo [org simple demo](http://demo.thi.ng/org-spec/), but I can't scroll down when I have long contents, how to add a scroll bar? 
![_20171011132940](https://user-images.githubusercontent.com/12882642/31423593-441f0e96-ae88-11e7-9c49-abc131447088.png)

Thank you.

**Comment by svauban** [comment]
Hello. The style seem to have been customized - as, in the original version, there is ALWAYS a scrollbar (which is annoying, because we should only see if when needed). Apparently, one has removed it in the theme you use.

**Comment by leolle** [comment]
thank you, how can I get the original theme files please?

**Comment by fniessen** [comment]
Follow the instructions on the README page (on the GitHub project). It should tell you everything you need to do. If not, come back.

**Comment by leolle** [comment]
@fniessen I can't find the style files I mentioned in this respository, there are only two themes, bigblow and readtheorg, I tried the theme at this link [https://github.com/fniessen/refcard-org-mode](refcard org mode), which is the original org html theme.
