### ISSUE TITLE
Assigning a maintainer?

### ISSUE THREAD

**Issue by kkweon** [fniessen/org-html-themes#68]
Considering the last push was done a half year ago, it seems it’s no longer maintained. If you dont have a time, maybe assign one from the community to maintain the project. We are willing to help to keep this awesome project alive.

I would love to see 
- Make the bigblow responsive
- Add new themes 

But nobody wants to risk his time when it is possibly no longer maintained.

**Comment by fniessen** [comment]
Hello. Just to make the things clear, yes I do have little time right now - though the radar is getting (a bit)clearer for the future. And, no, I do not intend to give away my project as is, at least not right now.

I'm eveing planning to add other HTML themes in there.

Please now that, at any given moment, I'm ready to pull and integrate push requests from anybody. That does not require much time from me. But they aren't any (even if I just did merge the 2 that were on my plate).

At any given moment, I'm willing to look at any contribution from you or anybody else. And, if I don't, ping me, and I'll do.

**Comment by academikuser** [comment]
That tufte-css that just frontpaged hackernews would be a nice theme.

On 7 November 2017 00:42:02 GMT+07:00, Fabrice Niessen <notifications@github.com> wrote:
>Hello. Just to make the things clear, yes I do have little time right
>now - though the radar is getting (a bit)clearer for the future. And,
>no, I do not intend to give away my project as is, at least not right
>now.
>
>I'm eveing planning to add other HTML themes in there.
>
>Please now that, at any given moment, I'm ready to pull and integrate
>push requests from anybody. That does not require much time from me.
>But they aren't any (even if I just did merge the 2 that were on my
>plate).
>
>At any given moment, I'm willing to look at any contribution from you
>or anybody else. And, if I don't, ping me, and I'll do.
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/fniessen/org-html-themes/issues/68#issuecomment-342227107

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by fniessen** [comment]
Are you willing to give a go at it?

**Comment by academikuser** [comment]
What if it was fixed at the current state and named org-html-themes-core?
 Then any new themes would have to go into org-html-themes-community //
 org-html-themes-modern // org-html-themes-academic if anyone made
something new.
