### ISSUE TITLE
TOC doesn't scroll properly

### ISSUE THREAD

**Issue by Krish95** [fniessen/org-html-themes#69]
Thank you for the awesome themes. 

The scroll bar of toc in readtheorg theme isn't working as expected. It shows all my sections at first and as I scroll down sections start disappearing from the list, and reappears when I scroll through the entire document. The major difficulty is in scrolling through toc instead of the document. 
![issue](https://user-images.githubusercontent.com/7701992/33306913-8c183d8a-d43a-11e7-9f41-435988e7f809.gif)

**Comment by Krish95** [comment]
Can you please help solve this?

**Comment by fniessen** [comment]
I won't be able, I fear. I've already done as much as I could to get something nice, in most standard cases (smaller TOC), but unfortunately I'm no CSS expert.

I'm sure it's solvable; it's only that I don't have the knowledge to correctly fix that.

**Comment by Krish95** [comment]
Thank you for the work. I really appreciate your efforts.

**Comment by malcook** [comment]
@Krish95  - did you ever resolve this?  

I am similarly afflicted.  

I find the problem to be an interaction between stickyTableHeaders and scrollspy.

If I change readtheorg.js to comment out one line, like this:
```
    // $('table').stickyTableHeaders();
```
then my scrolling problems go away (and scrollspy works as desired, keeping the TOC in sync with the current scroll position, even through tables).

Perhaps this is a clue to a solution, @fniessen ?  

BTW: I tried to see if using the latest version of [jmosbech/StickyTableHeaders](https://github.com/jmosbech) might resolve the problem, but it did not.

**Comment by fniessen** [comment]
Dear @malcook , thanks for the tip!  I've applied it, as you've done a good analysis of it. We'll whether we get good or bad feedback.

**Comment by fniessen** [comment]
I'll close this - hoping that it can be properly out of our way...
