### ISSUE TITLE
Sticky Table Headers

### ISSUE THREAD

**Issue by titaniumbones** [fniessen/org-html-themes#7]
I'm not sure how common a use-case this is, but I have some files with long tables containing lengthy text -- I use html export mostly so I can look at the whole table properly. For this I like to have "sticky" table headers. I can get this by adding JQuery Sticky Table Headers to the js scripts:

https://github.com/jmosbech/StickyTableHeaders

and then including a trivial bit of code:
```
$(document).ready ( function(){
    $('table').stickyTableHeaders();
});
```
It looks like Floatthread (http://mkoryak.github.io/floatThead/#) might also work, though it seems to add an unhelpfully narrow ~width~ to the table CSS.  

I'm wondering whether it's worth including this in bigblow? Maybe lots of people would like it?

**Comment by fniessen** [comment]
Any such solution certainly is interesting for all of us. Would you accept looking at how to plug it in the current CSS/JS files?

**Comment by titaniumbones** [comment]
Not sure how to attach at pull request but I have a patch in https://github.com/fniessen/org-html-themes/pull/14

**Comment by titaniumbones** [comment]
Note: in readtheorg, trnsparent background of table headers makes it a little hard to read them as you scroll up; adding 

th {
  background-color: white;
}
to the CSS should fix that.

**Comment by fniessen** [comment]
Transparent background removed (pushed on GitHub, not yet on Pirilampo).
