### ISSUE TITLE
Unknown syntax for info, tip, note or warning boxes

### ISSUE THREAD

**Issue by novoid** [fniessen/org-html-themes#72]
Hi!

I found
http://www.pirilampo.org/org-mode/syntax/#outline-container-orgheadline54
and https://github.com/fniessen/org-html-themes

Could you please explain how the syntax for info, tip, note or
warning boxes is?

This is not a standard Org-mode syntax and I could not find out how
to do it.

Thanks!

PS: The contact form of your web page does not work: Internal Server Error

**Comment by fniessen** [comment]
Dear novoid, the syntax for info, for example, is:

    #+begin_info
    This is extra info
    #+end_info

You can put whatever you want to create LaTeX environments or HTML DIV sections...

See my Org mode refcard (a GitHub project) for more info, and many examples.

PS- Thx for the info about my web site (a little unmanaged, to be honest).
