### ISSUE TITLE
bootstrap or foundation?

### ISSUE THREAD

**Issue by titaniumbones** [fniessen/org-html-themes#8]
just wondering if yoiu'd be interested in building a style that loads either Twitter Bootstrap or Zurb foundatoin -- I have gotten used to some of hte typography in these frameworks and miss those elements.  but I odn't want to miss hte cool features of bigblow. 

I see there's an ox-twbs for twitter:
https://github.com/marsmining/ox-twbs
Might be a starting point?

Thank you for this, it's awesome.

**Comment by fniessen** [comment]
Would you try and isolate the faces to import as a one-liner, such as:

@import url(https://fonts.googleapis.com/css?family=...
(or similar)

I'd enjoy giving it a chance.

Thanks for your comment.

**Comment by fniessen** [comment]
Closing this -- if no further news.
