### ISSUE TITLE
How can I use this package?

### ISSUE THREAD

**Issue by mrbig033** [fniessen/org-html-themes#81]
The readme only says

>  you just need to clone the Org-HTML themes project

Where should I clone it to, and how can I initialize it?

**Comment by fniessen** [comment]
You need to clone it (with git commands) or to download it somewhere on your HD -- as a ZIP file.
Then, type the right path to the file, and you should be gone.

Just for testing, you could also simply copy/paste the few "https" lines inside your Org buffer.

**Comment by mrbig033** [comment]
This is not an issue:
> ou need to clone it (with git commands) or to download it somewhere on your HD -- as a ZIP file.

Type where?
> Then, type the right path to the file, and you should be gone.

I don't know what you mean by that:
> Just for testing, you could also simply copy/paste the few "https" lines inside your Org buffer.

I find hostile that you closed an issue before actually solving it.

If this tool is only meant for programmers or people able to read your mind, please make it clear on the readme.

**Comment by fniessen** [comment]
Dear @mrbig033, download the project as a ZIP file, and put it, for example, in C:\repos\org-html-themes.

Then, type this in your Org file:

#+SETUPFILE: C:/repos/org-html-themes/setup/theme-readtheorg.setup

and you should get it.

I do have the impression that this is already documented in the README.org.  Please submit changes/fixes if you feel that should be better described/explained.
