### ISSUE TITLE
https://www.pirilampo.org/ is down

### ISSUE THREAD

**Issue by shlomi-nx** [fniessen/org-html-themes#82]
Causing the page to be displayed as naked html.

The fix is actually rather trivial, all that has to happen is that @fniessen will enable github-pages, and fix (or add) the proper setup files (see below).

I have cloned this repo and done just that, and it works fine. Just put this at the top of your org file:
`#+SETUPFILE: https://shlomiv.github.io/org-html-themes/setup/theme-readtheorg.setup`

The contents of the changed setup file have changed to:
```
# -*- mode: org; -*-

#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://shlomiv.github.io/org-html-themes/styles/readtheorg/css/htmlize.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://shlomiv.github.io/org-html-themes/styles/readtheorg/css/readtheorg.css"/>

#+HTML_HEAD: <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
#+HTML_HEAD: <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="https://shlomiv.github.io/org-html-themes/styles/js/jquery.stickytableheaders.min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="https://shlomiv.github.io/org-html-themes/styles/readtheorg/js/readtheorg.js"></script>
```

However, I would much rather this repo to be exposed through github pages than my own, as this is the goto place where all org-mode lovers go to get beautiful css-s.

Thanks,
Shlomi

**Comment by fniessen** [comment]
I'm trying hard to get the DNS problem fixed -- change of ISP...
But I'm striving for time.
Would you have a short description of what I should do, please send it to me, I'd love to improve this situation, for now and later.

**Comment by jarvisschultz** [comment]
Essentially @shlomi-nx fixed the issue by relying on [GitHub Pages](https://pages.github.com/) to host the CSS and JS files (although it doesn't seem like he pushed to a `gh-pages` branch so I'm not quite sure how he managed to get the content at the URLs he's using). Regardless, IMO, that seems like a solid idea for this repo too. GitHub has paid engineers to ensure their servers stay up, and people relying on this package aren't then depending on you to keep a site up-and-running.

**Comment by jarvisschultz** [comment]
Ahhh I should have done research before submitting that comment. Here's a quick set of steps that I think could get this repo to stop relying on your website:

1. Enable GitHub pages on the `master` branch by following [GitHub's instructions](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#enabling-github-pages-to-publish-your-site-from-master-or-gh-pages)
2. Push a commit to `master` that edits both [theme-readtheorg.setup](https://github.com/fniessen/org-html-themes/blob/master/setup/theme-readtheorg.setup) and [theme-bigblow.setup](https://github.com/fniessen/org-html-themes/blob/master/setup/theme-bigblow.setup) where you replace all references to `https://www.pirilampo.org` with `https://fniessen.github.io/org-html-themes`. One-liner to do this from the `setup` dir of the repo: `sed -i 's/www.pirilampo.org/fniessen.github.io\/org-html-themes/g' ./*`

**Comment by shlomi-nx** [comment]
Sorry for not mentioning that I used the `master` branch for the github pages. I guess we are on different time zones as I just work up and saw all this activity.

**Comment by fniessen** [comment]
Thanks for your pieces of advice. Sooo simple…

Can you confirm it's OK from your point of view as well?  If yes, then close the issue.

**Comment by shlomi-nx** [comment]
This works perfectly on my end, thanks!

I would also add to the main Readme file another option of usage: 
```
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup
```
This way newcomers dont have to git clone or anything, just put this line and everything should work.

Another thing I would have added to the doc is how to override particular tags, I know it took me a while to find and wish it was accessible to me, something like:
```
# To change the background of source block:
#+HTML_HEAD: <style>pre.src{background:#343131;color:white;} </style>
```

**Comment by fniessen** [comment]
Thanks a lot to both of you!  It helped getting this back on track in a relatively limited amount of time...
