### ISSUE TITLE
ReadTheOrg doesn't show TOC beyond the top level, and has background quirks

### ISSUE THREAD

**Issue by zilti** [fniessen/org-html-themes#83]
[Screenshot](https://i.imgur.com/DERw2YJ.png)

I have set `#+OPTIONS:        toc:3 h:4 html-postamble:auto html-preamble:t tex:t` in my setupfile. The screenshot is pretty self explanatory. What can I do about that?

**Comment by fniessen** [comment]
Can you publish an ECM, that is a Minimal Complete Example of the problem?  Minimal is self explanatory, and Complete means it allows to reproduce the problem.

**Comment by zilti** [comment]
[Is this helpful?](https://lyrion.ch/share/videocapture/config.html)

**Comment by fniessen** [comment]
Sorry, but no. I was asking for a complete and *minimal* Org file to play with -- where you do have the problem. I don't have more time to debug problems which may have nothing to do with the themes I share on GitHub.

**Comment by kuzmin-maxim** [comment]
You can scroll to the subheading or click on top level heading to unfold it.

**Comment by fniessen** [comment]
Also check you options in the header of the Org file:
#+OPTIONS:   H:4 num:t toc:4
