### ISSUE TITLE
I can't use the local setup file, though I can use the remote one.

### ISSUE THREAD

**Issue by karrot42** [fniessen/org-html-themes#90]
I'm sorry if this problem is kind of something really dumb on my part but, I just can't figure out any way to get it to work from a locally cloned file.

so 

`#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup`

works flawlessly but when I put

`#+SETUPFILE: /Users/karrot/org/org-html-themes/setup/theme-readtheorg-local.setup'

does not work and

`#+SETUPFILE: /Users/karrot/org/org-html-themes/setup/readtheorg-local.setup` 

doesn't work either.  I actually tried several variations, but none of them work.

That paths are copy and pasted, I've tried a lot fo stuff and I directly cloned it, and I just can't figure out what is going on.  Any help would be much appreciated.

**Comment by nico202** [comment]
what do you mean with "does not work"? Do the export fail? Do you load it in the browser and you cannot see the template?

**Comment by karrot42** [comment]
> what do you mean with "does not work"? Do the export fail? Do you load it in the browser and you cannot see the template?

Sorry, it exports but uses the default(?) template.

**Comment by nico202** [comment]
you need to copy (or symlink) the "style" folder in the directory of the html file. you can see some error (if it's missing) in firefox console (f12)

**Comment by fniessen** [comment]
@nico202 Thanks for helping, mate!

**Comment by karrot42** [comment]
> you need to copy (or symlink) the "style" folder in the directory of the html file. you can see some error (if it's missing) in firefox console (f12)

Just wanted to say this worked, but I am a bit curious as to why if I use the remote file, or even download the remote file and then point at that for exporting the exported file is a lone .html file that can be moved anywhere and works without having to be in the same directory as the style directory.

**Comment by jcguu95** [comment]
I have created another issue that addresses this problem. Indeed, this is a little one that can be fixed easily, but I believe the instruction should be clarified.

**Comment by fniessen** [comment]
Dear @jcguu95 , would you give it a try?  TIA!

**Comment by anupam312nwd** [comment]
> you need to copy (or symlink) the "style" folder in the directory of the html file. you can see some error (if it's missing) in firefox console (f12)

How do I create a symlink of the "style" folder? I don't know what "style" folder is.
I tried ```ln -s ~/Dropbox/Org ~/Coding/github/org-html-themes``` but it didn't work. 
Thanks!

**Comment by seahawk1986** [comment]
Nearly a month ago in https://github.com/fniessen/org-html-themes/commit/385e8a473eba2fa30e9e891dfc1e0fa3c9a7bf3d the `styles` folder was renamed to `src`.
