### ISSUE TITLE
MaxCDN is now StackPath

### ISSUE THREAD

**Issue by mahito1594** [fniessen/org-html-themes#92]
Dear fniessen

I found that [MaxCDN is now StackPath](https://www.stackpath.com/maxcdn/).  So we probably should replace `maxcdn.bootstrapcdn.com` with `stackpath.bootstrapcdn.com` in CSS files.

Yesterday, I failed to load `http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js` (but I success today), and hence got the error `Type error: $(...).scrollspy is not function`.

I am very sorry for not being familiar with CSS nor JavaScript, but I would like to ask your opinion.

Thanks,

**Comment by mahito1594** [comment]
Sorry, this is the problem of my web browser (Firefox v70.0.1 on macOS).  Adding a security exception for MaxCDN, ReadTheOrg works well.

**Comment by fniessen** [comment]
Dear @mahito1594 , sorry for not responding earlier… Well kept the mail ;-)

If you still think the suggested change would be advised, let me know.

**Comment by fniessen** [comment]
If not, you can safely close the issue, then.

**Comment by mahito1594** [comment]
Thank you for your reply!

I think, there may be no problem except the invalid SSL certificate for `maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js`.  I am very sorry but I can not determine whether my suggestion would be advised or not.  Anyway, I shall close this issue.

I apologize for not telling you that I appreciate your great ReadTheOrg theme.  Thanks!

**Comment by fniessen** [comment]
OK, thanks for the info. Would you know it's advised to do the change, please let me know.

Best regards.
