### ISSUE TITLE
license and tagged release?

### ISSUE THREAD

**Issue by sten0** [fniessen/org-html-themes#93]
Hi @fniessen,

I discovered this project while working on generating Ivy/Counsel/Swiper's HTML exported documentation, I maintain its Debian package, and I think org-html-themes would be a useful addition to Debian's archive.  Two blockers to this are the absence of a license, and an absence of a tagged release.

For the license, it would need to be be one of these [DFSG-compatible_Licenses.](https://wiki.debian.org/DFSGLicenses#DFSG-compatible_Licenses)  Additionally, it would need to be compatible with the GPL, and compatible with the GDFL (no invariant sections), because otherwise Ivy/Counsel/Swiper HTML documentation becomes undistributable.  The OP of #49 raises an ethical issue about the spirit of a license rather than a license issue, because while fixation automatically grants copyright in Bern convention-adhering countries, license is only meaningful if and when a work is distributed.  Eg: if all users of a truly private fork of GPL software have access to the modified source code, then the legal obligations are fulfilled...this might only be a handful of developers.

That said I'm guessing for org-html-themes to become maximally popular a web-friendly license would probably be best.  Sadly I'm not familiar with their details, but the [Debian legal team](https://www.debian.org/legal) would be able to help, and the mailing list is responsive to inquiries of this kind.

Would you please consider prioritising these two issues?  After those are solved, I have to solve #46 in a Debian context (eg: complete functionality when offline).

Sincerely,
Nicholas

**Comment by fniessen** [comment]
Dear @sten0 , a quick answer better than a delayed one…

For the license, I'm not sure to understand your point, as it is licensed under GPLv3, and GPL is one of the compatible licenses in your link. Though, I could imagine changing that to another one, if needed.

For the tag, yes I can do that straight-away if that's OK it's a tag on the org-html-themes, not specifically on RTO (Read The Org). Though, I could imagine just upgrading the tag when there is something new for RTO.

(Any preference or requirement, regarding the "v" prefix?  With it or without it?)

**Comment by sten0** [comment]
Dear @fneissen,

Fabrice Niessen <notifications@github.com> writes:

> Dear @sten0 , a quick answer better than a delayed one…
>

Thank you for the quick reply, much appreciated!

> For the license, I'm not sure to understand your point, as it is
> licensed under GPLv3, and GPL is one of the compatible licenses in
> your link. Though, I could imagine changing that to another one, if
> needed.
>

Sorry I missed that, I was working from notes I had made and hadn't
noted that README.org had the copyright info and license declaration.  I
did however note that Debian ftpmasters would request the full-text
GPLv3 in-repo (or in the release tarball), conventionally named LICENSE
or COPYRIGHT.  For your convenience, here's a link

  https://www.gnu.org/licenses/gpl-3.0.txt

> For the tag, yes I can do that straight-away if that's OK it's a tag
> on the org-html-themes, not specifically on RTO (Read The
> Org). Though, I could imagine just upgrading the tag when there is
> something new for RTO.
>
> (Any preference or requirement, regarding the "v" prefix?  With it or
> without it?)
>

As you prefer! :-)


Regards,
Nicholas

**Comment by fniessen** [comment]
Dear @sten0 , I've added the LICENSE file, and tagged the project v1.0.0.

Is this OK for you?

(Thanks for using it, BTW.)

**Comment by sten0** [comment]
Dear @fneissen,

Fabrice Niessen <notifications@github.com> writes:

> Dear @sten0 , I've added the LICENSE file, and tagged the project v1.0.0.
>
> Is this OK for you?
>

Yup!  I've started the packaging, and have filed the ITP (Intent to
Package) here:

  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=944704

> (Thanks for using it, BTW.)

Thank you for writing it :-) The project has serious potential IMHO, and
I believe that in the years to come it could become a standard tool of
enthusiasts of Org-mode.  In particular I'm curious if someone will port
more Sphinx themes, how it could be used in an IOT of things gadget
pipeline, plus for standardising look & feel between projects documented
in Sphinx and Org.

@abo-abo, thank you for introducing me to it!  (p.s. sorry for the
belated reply WRT Ivy HTML docs, I hit another busy patch IRL)


Cheers,
Nicholas
