### ISSUE TITLE
Reference to private setupfile in styles/.../readtheorg.org

### ISSUE THREAD

**Issue by Whil-** [fniessen/org-html-themes#99]
Thanks for this nice pretty exporting configuration!

Just wanted to highlight one issue I just ran into when opening the styles/readtheorg/readtheorg.org file.

It seems there is a reference to a local setupfile on line 9 in that file:
`
#+SETUPFILE: ~/.dotfiles/org/theme-readtheorg-local-abs.setup
`

That should probably be refactored so the settings are included in the file itself. Or just removed. Just a head-up!

Take care
/Gustav

**Comment by fniessen** [comment]
Thanks for the tip!
